site_name: ImmuKT | Docs
theme:
  name: material
  features:
    - navigation.instant
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      accent: teal
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      accent: teal
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
repo_url: https://github.com/PegasisForever/immukt
edit_uri: edit/master/docs/docs/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences